-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity coo_enc_outputMatrix_Pipeline_VITIS_LOOP_46_1_VITIS_LOOP_47_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    tmp_num0 : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_num1 : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_num2 : IN STD_LOGIC_VECTOR (31 downto 0);
    bound : IN STD_LOGIC_VECTOR (63 downto 0);
    M : IN STD_LOGIC_VECTOR (31 downto 0);
    trunc_ln : IN STD_LOGIC_VECTOR (13 downto 0);
    matrix_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    matrix_ce0 : OUT STD_LOGIC;
    matrix_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    out_r_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    out_r_TVALID : OUT STD_LOGIC;
    out_r_TREADY : IN STD_LOGIC;
    tmp_num0_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    tmp_num0_1_out_ap_vld : OUT STD_LOGIC;
    tmp_num1_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    tmp_num1_1_out_ap_vld : OUT STD_LOGIC;
    tmp_num2_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    tmp_num2_1_out_ap_vld : OUT STD_LOGIC;
    tmp_num3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    tmp_num3_out_ap_vld : OUT STD_LOGIC;
    grp_fu_101_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_101_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_101_p_ce : OUT STD_LOGIC;
    grp_fu_93_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_93_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_93_p_ce : OUT STD_LOGIC;
    grp_fu_229_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_229_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_229_p_ce : OUT STD_LOGIC;
    grp_fu_232_p_din0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_232_p_din1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_232_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_232_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_232_p_ce : OUT STD_LOGIC );
end;


architecture behav of coo_enc_outputMatrix_Pipeline_VITIS_LOOP_46_1_VITIS_LOOP_47_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv64_3EB0C6F7A0B5ED8D : STD_LOGIC_VECTOR (63 downto 0) := "0011111010110000110001101111011110100000101101011110110110001101";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv52_0 : STD_LOGIC_VECTOR (51 downto 0) := "0000000000000000000000000000000000000000000000000000";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal out_r_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal icmp_ln46_reg_805 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_reg_805_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln49_reg_880 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_V_load11_reg_888 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal p_V_load_1_reg_884 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal p_V_1_reg_924 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_num3_1_reg_206 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_num2_2_reg_220 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_num1_2_reg_234 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_num0_2_reg_248 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln46_fu_450_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter2 : BOOLEAN;
    signal ap_predicate_op150_write_state11 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state11_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln46_reg_805_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal j_load_reg_809 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln47_fu_467_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_814 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_1_fu_478_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln46_fu_501_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln46_reg_829 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state4_pp0_stage2_iter0 : BOOLEAN;
    signal ap_block_state7_pp0_stage2_iter1 : BOOLEAN;
    signal ap_predicate_op124_write_state10 : BOOLEAN;
    signal ap_block_state10_pp0_stage2_iter2 : BOOLEAN;
    signal ap_block_state10_io : BOOLEAN;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal select_ln46_reg_829_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_num0_10_mid2_reg_839 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_num0_10_mid2_reg_839_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_num2_8_reg_852 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state3_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state6_pp0_stage1_iter1 : BOOLEAN;
    signal ap_predicate_op106_write_state9 : BOOLEAN;
    signal ap_block_state9_pp0_stage1_iter2 : BOOLEAN;
    signal ap_block_state9_io : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal tmp_num2_8_reg_852_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln356_fu_542_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln49_fu_565_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_reg_870 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_1_fu_571_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_1_reg_875 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln49_fu_581_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_num3_5_reg_892 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_num2_5_reg_900 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_num1_5_reg_908 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_num0_5_reg_916 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_V_1_fu_660_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_condition_pp0_flush_enable : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter2_state9 : STD_LOGIC;
    signal ap_phi_reg_pp0_iter0_tmp_num3_1_reg_206 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_tmp_num3_1_reg_206 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter2_tmp_num3_1_reg_206 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_tmp_num2_2_reg_220 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_tmp_num2_2_reg_220 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter2_tmp_num2_2_reg_220 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_tmp_num1_2_reg_234 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_tmp_num1_2_reg_234 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter2_tmp_num1_2_reg_234 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_tmp_num0_2_reg_248 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_tmp_num0_2_reg_248 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter2_tmp_num0_2_reg_248 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_tmp_num3_3_phi_fu_265_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter3_tmp_num3_3_reg_262 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_tmp_num2_3_phi_fu_281_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter3_tmp_num2_3_reg_278 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_tmp_num1_3_phi_fu_297_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter3_tmp_num1_3_reg_294 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_tmp_num0_3_phi_fu_313_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter3_tmp_num0_3_reg_310 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_tmp_num3_4_phi_fu_329_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter3_tmp_num3_4_reg_326 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_tmp_num2_4_phi_fu_345_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter3_tmp_num2_4_reg_342 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_tmp_num1_4_phi_fu_361_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter3_tmp_num1_4_reg_358 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_tmp_num0_4_phi_fu_377_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter3_tmp_num0_4_reg_374 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln48_fu_522_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_90 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln47_fu_511_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_fu_94 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten_fu_98 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln46_fu_455_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_num3_fu_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_num2_1_fu_106 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_num1_1_fu_110 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_num0_1_fu_114 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_V_fu_118 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_V_2_fu_666_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_s_fu_618_p5 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal p_1_fu_647_p5 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_block_pp0_stage2_01001 : BOOLEAN;
    signal p_0_fu_693_p5 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal add_ln46_1_fu_472_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln48_fu_522_p0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_726_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal data_V_fu_526_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln368_fu_530_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal p_Result_s_fu_534_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln49_fu_547_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_4_fu_551_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln49_fu_561_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal or_ln49_fu_577_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln174_3_fu_614_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln174_2_fu_610_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln174_1_fu_606_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln174_fu_602_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln174_7_fu_643_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln174_6_fu_639_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln174_5_fu_635_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln174_4_fu_631_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln174_11_fu_689_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln174_10_fu_685_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln174_9_fu_681_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln174_8_fu_677_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_726_p0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_726_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_390_ce : STD_LOGIC;
    signal grp_fu_393_ce : STD_LOGIC;
    signal grp_fu_400_ce : STD_LOGIC;
    signal grp_fu_403_ce : STD_LOGIC;
    signal ap_block_pp0_stage2_00001 : BOOLEAN;
    signal grp_fu_726_ce : STD_LOGIC;
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component coo_enc_sitofp_32ns_32_4_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component coo_enc_fpext_32ns_64_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component coo_enc_dcmp_64ns_64ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component coo_enc_mac_muladd_14s_14s_14ns_14_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (13 downto 0);
        din1 : IN STD_LOGIC_VECTOR (13 downto 0);
        din2 : IN STD_LOGIC_VECTOR (13 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (13 downto 0) );
    end component;



begin
    mac_muladd_14s_14s_14ns_14_4_1_U20 : component coo_enc_mac_muladd_14s_14s_14ns_14_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 14,
        din1_WIDTH => 14,
        din2_WIDTH => 14,
        dout_WIDTH => 14)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_726_p0,
        din1 => trunc_ln,
        din2 => grp_fu_726_p2,
        ce => grp_fu_726_ce,
        dout => grp_fu_726_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_pp0_flush_enable)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif ((((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_condition_pp0_exit_iter2_state9)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_pp0_exit_iter2_state9) and (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter1;
                elsif ((((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter2_tmp_num0_2_reg_248_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((p_V_load_1_reg_884 = ap_const_lv2_0) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_phi_reg_pp0_iter2_tmp_num0_2_reg_248 <= tmp_num0_10_mid2_reg_839_pp0_iter2_reg;
            elsif ((((p_V_load_1_reg_884 = ap_const_lv2_2) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((p_V_load_1_reg_884 = ap_const_lv2_1) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((p_V_load_1_reg_884 = ap_const_lv2_3) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
                ap_phi_reg_pp0_iter2_tmp_num0_2_reg_248 <= tmp_num0_1_fu_114;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                ap_phi_reg_pp0_iter2_tmp_num0_2_reg_248 <= ap_phi_reg_pp0_iter1_tmp_num0_2_reg_248;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_tmp_num1_2_reg_234_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((p_V_load_1_reg_884 = ap_const_lv2_1) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_phi_reg_pp0_iter2_tmp_num1_2_reg_234 <= tmp_num0_10_mid2_reg_839_pp0_iter2_reg;
            elsif ((((p_V_load_1_reg_884 = ap_const_lv2_0) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((p_V_load_1_reg_884 = ap_const_lv2_2) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((p_V_load_1_reg_884 = ap_const_lv2_3) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
                ap_phi_reg_pp0_iter2_tmp_num1_2_reg_234 <= tmp_num1_1_fu_110;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                ap_phi_reg_pp0_iter2_tmp_num1_2_reg_234 <= ap_phi_reg_pp0_iter1_tmp_num1_2_reg_234;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_tmp_num2_2_reg_220_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((p_V_load_1_reg_884 = ap_const_lv2_2) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_phi_reg_pp0_iter2_tmp_num2_2_reg_220 <= tmp_num0_10_mid2_reg_839_pp0_iter2_reg;
            elsif ((((p_V_load_1_reg_884 = ap_const_lv2_0) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((p_V_load_1_reg_884 = ap_const_lv2_1) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((p_V_load_1_reg_884 = ap_const_lv2_3) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
                ap_phi_reg_pp0_iter2_tmp_num2_2_reg_220 <= tmp_num2_1_fu_106;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                ap_phi_reg_pp0_iter2_tmp_num2_2_reg_220 <= ap_phi_reg_pp0_iter1_tmp_num2_2_reg_220;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_tmp_num3_1_reg_206_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((p_V_load_1_reg_884 = ap_const_lv2_0) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((p_V_load_1_reg_884 = ap_const_lv2_2) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((p_V_load_1_reg_884 = ap_const_lv2_1) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
                ap_phi_reg_pp0_iter2_tmp_num3_1_reg_206 <= tmp_num3_fu_102;
            elsif (((p_V_load_1_reg_884 = ap_const_lv2_3) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_phi_reg_pp0_iter2_tmp_num3_1_reg_206 <= tmp_num0_10_mid2_reg_839_pp0_iter2_reg;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                ap_phi_reg_pp0_iter2_tmp_num3_1_reg_206 <= ap_phi_reg_pp0_iter1_tmp_num3_1_reg_206;
            end if; 
        end if;
    end process;

    i_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_fu_94 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln46_fu_450_p2 = ap_const_lv1_0))) then 
                i_fu_94 <= select_ln46_1_fu_478_p3;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                indvar_flatten_fu_98 <= ap_const_lv64_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln46_fu_450_p2 = ap_const_lv1_0))) then 
                indvar_flatten_fu_98 <= add_ln46_fu_455_p2;
            end if; 
        end if;
    end process;

    j_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                j_fu_90 <= ap_const_lv32_0;
            elsif (((icmp_ln46_reg_805 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                j_fu_90 <= add_ln47_fu_511_p2;
            end if; 
        end if;
    end process;

    p_V_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                p_V_fu_118 <= ap_const_lv2_3;
            elsif (((ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                p_V_fu_118 <= p_V_2_fu_666_p2;
            end if; 
        end if;
    end process;

    tmp_num0_1_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                tmp_num0_1_fu_114 <= tmp_num0;
            elsif (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_lv1_1 = and_ln49_reg_880) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                tmp_num0_1_fu_114 <= ap_phi_mux_tmp_num0_4_phi_fu_377_p8;
            end if; 
        end if;
    end process;

    tmp_num1_1_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                tmp_num1_1_fu_110 <= tmp_num1;
            elsif (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_lv1_1 = and_ln49_reg_880) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                tmp_num1_1_fu_110 <= ap_phi_mux_tmp_num1_4_phi_fu_361_p8;
            end if; 
        end if;
    end process;

    tmp_num2_1_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                tmp_num2_1_fu_106 <= tmp_num2;
            elsif (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_lv1_1 = and_ln49_reg_880) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                tmp_num2_1_fu_106 <= ap_phi_mux_tmp_num2_4_phi_fu_345_p8;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln46_reg_805_pp0_iter1_reg = ap_const_lv1_0))) then
                and_ln49_reg_880 <= and_ln49_fu_581_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                ap_phi_reg_pp0_iter1_tmp_num0_2_reg_248 <= ap_phi_reg_pp0_iter0_tmp_num0_2_reg_248;
                ap_phi_reg_pp0_iter1_tmp_num1_2_reg_234 <= ap_phi_reg_pp0_iter0_tmp_num1_2_reg_234;
                ap_phi_reg_pp0_iter1_tmp_num2_2_reg_220 <= ap_phi_reg_pp0_iter0_tmp_num2_2_reg_220;
                ap_phi_reg_pp0_iter1_tmp_num3_1_reg_206 <= ap_phi_reg_pp0_iter0_tmp_num3_1_reg_206;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln46_reg_805 <= icmp_ln46_fu_450_p2;
                icmp_ln46_reg_805_pp0_iter1_reg <= icmp_ln46_reg_805;
                icmp_ln46_reg_805_pp0_iter2_reg <= icmp_ln46_reg_805_pp0_iter1_reg;
                tmp_num0_10_mid2_reg_839_pp0_iter2_reg <= tmp_num0_10_mid2_reg_839;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln46_fu_450_p2 = ap_const_lv1_0))) then
                icmp_ln47_reg_814 <= icmp_ln47_fu_467_p2;
                j_load_reg_809 <= j_fu_90;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (icmp_ln46_reg_805_pp0_iter1_reg = ap_const_lv1_0))) then
                icmp_ln49_1_reg_875 <= icmp_ln49_1_fu_571_p2;
                icmp_ln49_reg_870 <= icmp_ln49_fu_565_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                p_V_1_reg_924 <= p_V_1_fu_660_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln49_fu_581_p2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln46_reg_805_pp0_iter1_reg = ap_const_lv1_0))) then
                p_V_load11_reg_888 <= p_V_fu_118;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln49_fu_581_p2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln46_reg_805_pp0_iter1_reg = ap_const_lv1_0))) then
                p_V_load_1_reg_884 <= p_V_fu_118;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln46_reg_805 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                select_ln46_reg_829 <= select_ln46_fu_501_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                select_ln46_reg_829_pp0_iter1_reg <= select_ln46_reg_829;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln46_reg_805 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_num0_10_mid2_reg_839 <= grp_fu_101_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                tmp_num0_2_reg_248 <= ap_phi_reg_pp0_iter2_tmp_num0_2_reg_248;
                tmp_num1_2_reg_234 <= ap_phi_reg_pp0_iter2_tmp_num1_2_reg_234;
                tmp_num2_2_reg_220 <= ap_phi_reg_pp0_iter2_tmp_num2_2_reg_220;
                tmp_num3_1_reg_206 <= ap_phi_reg_pp0_iter2_tmp_num3_1_reg_206;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                tmp_num0_5_reg_916 <= tmp_num0_1_fu_114;
                tmp_num1_5_reg_908 <= tmp_num1_1_fu_110;
                tmp_num2_5_reg_900 <= tmp_num2_1_fu_106;
                tmp_num3_5_reg_892 <= tmp_num3_fu_102;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln46_reg_805_pp0_iter1_reg = ap_const_lv1_0))) then
                tmp_num2_8_reg_852 <= matrix_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                tmp_num2_8_reg_852_pp0_iter2_reg <= tmp_num2_8_reg_852;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_lv1_1 = and_ln49_reg_880) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_num3_fu_102 <= ap_phi_mux_tmp_num3_4_phi_fu_329_p8;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter1, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    add_ln46_1_fu_472_p2 <= std_logic_vector(unsigned(i_fu_94) + unsigned(ap_const_lv32_1));
    add_ln46_fu_455_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_98) + unsigned(ap_const_lv64_1));
    add_ln47_fu_511_p2 <= std_logic_vector(unsigned(select_ln46_fu_501_p3) + unsigned(ap_const_lv32_1));
    and_ln49_fu_581_p2 <= (or_ln49_fu_577_p2 and grp_fu_232_p_dout0);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state12 <= ap_CS_fsm(4);
    ap_CS_fsm_state14 <= ap_CS_fsm(6);
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(out_r_TREADY, ap_enable_reg_pp0_iter3, ap_predicate_op150_write_state11)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (out_r_TREADY = ap_const_logic_0) and (ap_predicate_op150_write_state11 = ap_const_boolean_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(out_r_TREADY, ap_enable_reg_pp0_iter3, ap_predicate_op150_write_state11, ap_block_state11_io)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state11_io) or ((out_r_TREADY = ap_const_logic_0) and (ap_predicate_op150_write_state11 = ap_const_boolean_1))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(out_r_TREADY, ap_enable_reg_pp0_iter3, ap_predicate_op150_write_state11, ap_block_state11_io)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state11_io) or ((out_r_TREADY = ap_const_logic_0) and (ap_predicate_op150_write_state11 = ap_const_boolean_1))));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_01001_assign_proc : process(out_r_TREADY, ap_enable_reg_pp0_iter2, ap_predicate_op106_write_state9)
    begin
                ap_block_pp0_stage1_01001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (out_r_TREADY = ap_const_logic_0) and (ap_predicate_op106_write_state9 = ap_const_boolean_1));
    end process;


    ap_block_pp0_stage1_11001_assign_proc : process(out_r_TREADY, ap_enable_reg_pp0_iter2, ap_predicate_op106_write_state9, ap_block_state9_io)
    begin
                ap_block_pp0_stage1_11001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state9_io) or ((out_r_TREADY = ap_const_logic_0) and (ap_predicate_op106_write_state9 = ap_const_boolean_1))));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(out_r_TREADY, ap_enable_reg_pp0_iter2, ap_predicate_op106_write_state9, ap_block_state9_io)
    begin
                ap_block_pp0_stage1_subdone <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state9_io) or ((out_r_TREADY = ap_const_logic_0) and (ap_predicate_op106_write_state9 = ap_const_boolean_1))));
    end process;

        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_00001_assign_proc : process(out_r_TREADY, ap_enable_reg_pp0_iter2, ap_predicate_op124_write_state10)
    begin
                ap_block_pp0_stage2_00001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (out_r_TREADY = ap_const_logic_0) and (ap_predicate_op124_write_state10 = ap_const_boolean_1));
    end process;


    ap_block_pp0_stage2_01001_assign_proc : process(out_r_TREADY, ap_enable_reg_pp0_iter2, ap_predicate_op124_write_state10)
    begin
                ap_block_pp0_stage2_01001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (out_r_TREADY = ap_const_logic_0) and (ap_predicate_op124_write_state10 = ap_const_boolean_1));
    end process;


    ap_block_pp0_stage2_11001_assign_proc : process(out_r_TREADY, ap_enable_reg_pp0_iter2, ap_predicate_op124_write_state10, ap_block_state10_io)
    begin
                ap_block_pp0_stage2_11001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state10_io) or ((out_r_TREADY = ap_const_logic_0) and (ap_predicate_op124_write_state10 = ap_const_boolean_1))));
    end process;


    ap_block_pp0_stage2_subdone_assign_proc : process(out_r_TREADY, ap_enable_reg_pp0_iter2, ap_predicate_op124_write_state10, ap_block_state10_io)
    begin
                ap_block_pp0_stage2_subdone <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state10_io) or ((out_r_TREADY = ap_const_logic_0) and (ap_predicate_op124_write_state10 = ap_const_boolean_1))));
    end process;


    ap_block_state10_io_assign_proc : process(out_r_TREADY, ap_predicate_op124_write_state10)
    begin
                ap_block_state10_io <= ((out_r_TREADY = ap_const_logic_0) and (ap_predicate_op124_write_state10 = ap_const_boolean_1));
    end process;


    ap_block_state10_pp0_stage2_iter2_assign_proc : process(out_r_TREADY, ap_predicate_op124_write_state10)
    begin
                ap_block_state10_pp0_stage2_iter2 <= ((out_r_TREADY = ap_const_logic_0) and (ap_predicate_op124_write_state10 = ap_const_boolean_1));
    end process;


    ap_block_state11_io_assign_proc : process(out_r_TREADY, ap_predicate_op150_write_state11)
    begin
                ap_block_state11_io <= ((out_r_TREADY = ap_const_logic_0) and (ap_predicate_op150_write_state11 = ap_const_boolean_1));
    end process;


    ap_block_state11_pp0_stage0_iter3_assign_proc : process(out_r_TREADY, ap_predicate_op150_write_state11)
    begin
                ap_block_state11_pp0_stage0_iter3 <= ((out_r_TREADY = ap_const_logic_0) and (ap_predicate_op150_write_state11 = ap_const_boolean_1));
    end process;

        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage2_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage2_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state9_io_assign_proc : process(out_r_TREADY, ap_predicate_op106_write_state9)
    begin
                ap_block_state9_io <= ((out_r_TREADY = ap_const_logic_0) and (ap_predicate_op106_write_state9 = ap_const_boolean_1));
    end process;


    ap_block_state9_pp0_stage1_iter2_assign_proc : process(out_r_TREADY, ap_predicate_op106_write_state9)
    begin
                ap_block_state9_pp0_stage1_iter2 <= ((out_r_TREADY = ap_const_logic_0) and (ap_predicate_op106_write_state9 = ap_const_boolean_1));
    end process;


    ap_condition_pp0_exit_iter2_state9_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_condition_pp0_exit_iter2_state9 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter2_state9 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp0_flush_enable_assign_proc : process(ap_CS_fsm_pp0_stage2, icmp_ln46_reg_805, ap_block_pp0_stage2_subdone)
    begin
        if (((icmp_ln46_reg_805 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_condition_pp0_flush_enable <= ap_const_logic_1;
        else 
            ap_condition_pp0_flush_enable <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_tmp_num0_3_phi_fu_313_p8_assign_proc : process(icmp_ln46_reg_805_pp0_iter2_reg, and_ln49_reg_880, p_V_load11_reg_888, tmp_num0_2_reg_248, ap_phi_reg_pp0_iter3_tmp_num0_3_reg_310, grp_fu_93_p_dout0)
    begin
        if (((p_V_load11_reg_888 = ap_const_lv2_3) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0))) then 
            ap_phi_mux_tmp_num0_3_phi_fu_313_p8 <= grp_fu_93_p_dout0;
        elsif ((((p_V_load11_reg_888 = ap_const_lv2_0) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0)) or ((p_V_load11_reg_888 = ap_const_lv2_1) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0)) or ((p_V_load11_reg_888 = ap_const_lv2_2) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0)))) then 
            ap_phi_mux_tmp_num0_3_phi_fu_313_p8 <= tmp_num0_2_reg_248;
        else 
            ap_phi_mux_tmp_num0_3_phi_fu_313_p8 <= ap_phi_reg_pp0_iter3_tmp_num0_3_reg_310;
        end if; 
    end process;


    ap_phi_mux_tmp_num0_4_phi_fu_377_p8_assign_proc : process(icmp_ln46_reg_805_pp0_iter2_reg, and_ln49_reg_880, p_V_1_reg_924, tmp_num2_8_reg_852_pp0_iter2_reg, ap_phi_mux_tmp_num0_3_phi_fu_313_p8, ap_phi_reg_pp0_iter3_tmp_num0_4_reg_374)
    begin
        if (((ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (p_V_1_reg_924 = ap_const_lv2_0))) then 
            ap_phi_mux_tmp_num0_4_phi_fu_377_p8 <= tmp_num2_8_reg_852_pp0_iter2_reg;
        elsif ((((ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (p_V_1_reg_924 = ap_const_lv2_2)) or ((ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (p_V_1_reg_924 = ap_const_lv2_1)) or ((ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (p_V_1_reg_924 = ap_const_lv2_3)))) then 
            ap_phi_mux_tmp_num0_4_phi_fu_377_p8 <= ap_phi_mux_tmp_num0_3_phi_fu_313_p8;
        else 
            ap_phi_mux_tmp_num0_4_phi_fu_377_p8 <= ap_phi_reg_pp0_iter3_tmp_num0_4_reg_374;
        end if; 
    end process;


    ap_phi_mux_tmp_num1_3_phi_fu_297_p8_assign_proc : process(icmp_ln46_reg_805_pp0_iter2_reg, and_ln49_reg_880, p_V_load11_reg_888, tmp_num1_2_reg_234, ap_phi_reg_pp0_iter3_tmp_num1_3_reg_294, grp_fu_93_p_dout0)
    begin
        if (((p_V_load11_reg_888 = ap_const_lv2_0) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0))) then 
            ap_phi_mux_tmp_num1_3_phi_fu_297_p8 <= grp_fu_93_p_dout0;
        elsif ((((p_V_load11_reg_888 = ap_const_lv2_3) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0)) or ((p_V_load11_reg_888 = ap_const_lv2_1) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0)) or ((p_V_load11_reg_888 = ap_const_lv2_2) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0)))) then 
            ap_phi_mux_tmp_num1_3_phi_fu_297_p8 <= tmp_num1_2_reg_234;
        else 
            ap_phi_mux_tmp_num1_3_phi_fu_297_p8 <= ap_phi_reg_pp0_iter3_tmp_num1_3_reg_294;
        end if; 
    end process;


    ap_phi_mux_tmp_num1_4_phi_fu_361_p8_assign_proc : process(icmp_ln46_reg_805_pp0_iter2_reg, and_ln49_reg_880, p_V_1_reg_924, tmp_num2_8_reg_852_pp0_iter2_reg, ap_phi_mux_tmp_num1_3_phi_fu_297_p8, ap_phi_reg_pp0_iter3_tmp_num1_4_reg_358)
    begin
        if (((ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (p_V_1_reg_924 = ap_const_lv2_1))) then 
            ap_phi_mux_tmp_num1_4_phi_fu_361_p8 <= tmp_num2_8_reg_852_pp0_iter2_reg;
        elsif ((((ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (p_V_1_reg_924 = ap_const_lv2_2)) or ((ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (p_V_1_reg_924 = ap_const_lv2_3)) or ((ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (p_V_1_reg_924 = ap_const_lv2_0)))) then 
            ap_phi_mux_tmp_num1_4_phi_fu_361_p8 <= ap_phi_mux_tmp_num1_3_phi_fu_297_p8;
        else 
            ap_phi_mux_tmp_num1_4_phi_fu_361_p8 <= ap_phi_reg_pp0_iter3_tmp_num1_4_reg_358;
        end if; 
    end process;


    ap_phi_mux_tmp_num2_3_phi_fu_281_p8_assign_proc : process(icmp_ln46_reg_805_pp0_iter2_reg, and_ln49_reg_880, p_V_load11_reg_888, tmp_num2_2_reg_220, ap_phi_reg_pp0_iter3_tmp_num2_3_reg_278, grp_fu_93_p_dout0)
    begin
        if (((p_V_load11_reg_888 = ap_const_lv2_1) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0))) then 
            ap_phi_mux_tmp_num2_3_phi_fu_281_p8 <= grp_fu_93_p_dout0;
        elsif ((((p_V_load11_reg_888 = ap_const_lv2_3) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0)) or ((p_V_load11_reg_888 = ap_const_lv2_0) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0)) or ((p_V_load11_reg_888 = ap_const_lv2_2) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0)))) then 
            ap_phi_mux_tmp_num2_3_phi_fu_281_p8 <= tmp_num2_2_reg_220;
        else 
            ap_phi_mux_tmp_num2_3_phi_fu_281_p8 <= ap_phi_reg_pp0_iter3_tmp_num2_3_reg_278;
        end if; 
    end process;


    ap_phi_mux_tmp_num2_4_phi_fu_345_p8_assign_proc : process(icmp_ln46_reg_805_pp0_iter2_reg, and_ln49_reg_880, p_V_1_reg_924, tmp_num2_8_reg_852_pp0_iter2_reg, ap_phi_mux_tmp_num2_3_phi_fu_281_p8, ap_phi_reg_pp0_iter3_tmp_num2_4_reg_342)
    begin
        if (((ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (p_V_1_reg_924 = ap_const_lv2_2))) then 
            ap_phi_mux_tmp_num2_4_phi_fu_345_p8 <= tmp_num2_8_reg_852_pp0_iter2_reg;
        elsif ((((ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (p_V_1_reg_924 = ap_const_lv2_1)) or ((ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (p_V_1_reg_924 = ap_const_lv2_3)) or ((ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (p_V_1_reg_924 = ap_const_lv2_0)))) then 
            ap_phi_mux_tmp_num2_4_phi_fu_345_p8 <= ap_phi_mux_tmp_num2_3_phi_fu_281_p8;
        else 
            ap_phi_mux_tmp_num2_4_phi_fu_345_p8 <= ap_phi_reg_pp0_iter3_tmp_num2_4_reg_342;
        end if; 
    end process;


    ap_phi_mux_tmp_num3_3_phi_fu_265_p8_assign_proc : process(icmp_ln46_reg_805_pp0_iter2_reg, and_ln49_reg_880, p_V_load11_reg_888, tmp_num3_1_reg_206, ap_phi_reg_pp0_iter3_tmp_num3_3_reg_262, grp_fu_93_p_dout0)
    begin
        if ((((p_V_load11_reg_888 = ap_const_lv2_3) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0)) or ((p_V_load11_reg_888 = ap_const_lv2_0) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0)) or ((p_V_load11_reg_888 = ap_const_lv2_1) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0)))) then 
            ap_phi_mux_tmp_num3_3_phi_fu_265_p8 <= tmp_num3_1_reg_206;
        elsif (((p_V_load11_reg_888 = ap_const_lv2_2) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0))) then 
            ap_phi_mux_tmp_num3_3_phi_fu_265_p8 <= grp_fu_93_p_dout0;
        else 
            ap_phi_mux_tmp_num3_3_phi_fu_265_p8 <= ap_phi_reg_pp0_iter3_tmp_num3_3_reg_262;
        end if; 
    end process;


    ap_phi_mux_tmp_num3_4_phi_fu_329_p8_assign_proc : process(icmp_ln46_reg_805_pp0_iter2_reg, and_ln49_reg_880, p_V_1_reg_924, tmp_num2_8_reg_852_pp0_iter2_reg, ap_phi_mux_tmp_num3_3_phi_fu_265_p8, ap_phi_reg_pp0_iter3_tmp_num3_4_reg_326)
    begin
        if ((((ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (p_V_1_reg_924 = ap_const_lv2_2)) or ((ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (p_V_1_reg_924 = ap_const_lv2_1)) or ((ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (p_V_1_reg_924 = ap_const_lv2_0)))) then 
            ap_phi_mux_tmp_num3_4_phi_fu_329_p8 <= ap_phi_mux_tmp_num3_3_phi_fu_265_p8;
        elsif (((ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (p_V_1_reg_924 = ap_const_lv2_3))) then 
            ap_phi_mux_tmp_num3_4_phi_fu_329_p8 <= tmp_num2_8_reg_852_pp0_iter2_reg;
        else 
            ap_phi_mux_tmp_num3_4_phi_fu_329_p8 <= ap_phi_reg_pp0_iter3_tmp_num3_4_reg_326;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_tmp_num0_2_reg_248 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tmp_num1_2_reg_234 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tmp_num2_2_reg_220 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tmp_num3_1_reg_206 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter3_tmp_num0_3_reg_310 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter3_tmp_num0_4_reg_374 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter3_tmp_num1_3_reg_294 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter3_tmp_num1_4_reg_358 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter3_tmp_num2_3_reg_278 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter3_tmp_num2_4_reg_342 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter3_tmp_num3_3_reg_262 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter3_tmp_num3_4_reg_326 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op106_write_state9_assign_proc : process(icmp_ln46_reg_805_pp0_iter2_reg, and_ln49_reg_880, p_V_load_1_reg_884)
    begin
                ap_predicate_op106_write_state9 <= ((p_V_load_1_reg_884 = ap_const_lv2_0) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op124_write_state10_assign_proc : process(icmp_ln46_reg_805_pp0_iter2_reg, and_ln49_reg_880, p_V_load11_reg_888)
    begin
                ap_predicate_op124_write_state10 <= ((p_V_load11_reg_888 = ap_const_lv2_3) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op150_write_state11_assign_proc : process(icmp_ln46_reg_805_pp0_iter2_reg, and_ln49_reg_880, p_V_1_reg_924)
    begin
                ap_predicate_op150_write_state11 <= ((ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (p_V_1_reg_924 = ap_const_lv2_0));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bitcast_ln174_10_fu_685_p1 <= ap_phi_mux_tmp_num2_3_phi_fu_281_p8;
    bitcast_ln174_11_fu_689_p1 <= ap_phi_mux_tmp_num3_3_phi_fu_265_p8;
    bitcast_ln174_1_fu_606_p1 <= tmp_num1_1_fu_110;
    bitcast_ln174_2_fu_610_p1 <= tmp_num2_1_fu_106;
    bitcast_ln174_3_fu_614_p1 <= tmp_num3_fu_102;
    bitcast_ln174_4_fu_631_p1 <= ap_phi_reg_pp0_iter2_tmp_num0_2_reg_248;
    bitcast_ln174_5_fu_635_p1 <= ap_phi_reg_pp0_iter2_tmp_num1_2_reg_234;
    bitcast_ln174_6_fu_639_p1 <= ap_phi_reg_pp0_iter2_tmp_num2_2_reg_220;
    bitcast_ln174_7_fu_643_p1 <= ap_phi_reg_pp0_iter2_tmp_num3_1_reg_206;
    bitcast_ln174_8_fu_677_p1 <= ap_phi_mux_tmp_num0_3_phi_fu_313_p8;
    bitcast_ln174_9_fu_681_p1 <= ap_phi_mux_tmp_num1_3_phi_fu_297_p8;
    bitcast_ln174_fu_602_p1 <= tmp_num0_1_fu_114;
    bitcast_ln356_fu_542_p1 <= p_Result_s_fu_534_p3;
    bitcast_ln49_fu_547_p1 <= grp_fu_229_p_dout0;
    data_V_fu_526_p1 <= matrix_q0;
    grp_fu_101_p_ce <= grp_fu_390_ce;
    grp_fu_101_p_din0 <= select_ln46_1_fu_478_p3;
    grp_fu_229_p_ce <= grp_fu_400_ce;
    grp_fu_229_p_din0 <= bitcast_ln356_fu_542_p1;
    grp_fu_232_p_ce <= grp_fu_403_ce;
    grp_fu_232_p_din0 <= grp_fu_229_p_dout0;
    grp_fu_232_p_din1 <= ap_const_lv64_3EB0C6F7A0B5ED8D;
    grp_fu_232_p_opcode <= ap_const_lv5_2;

    grp_fu_390_ce_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_block_pp0_stage2_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            grp_fu_390_ce <= ap_const_logic_1;
        else 
            grp_fu_390_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_393_ce_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_block_pp0_stage2_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            grp_fu_393_ce <= ap_const_logic_1;
        else 
            grp_fu_393_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_400_ce_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage2_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then 
            grp_fu_400_ce <= ap_const_logic_1;
        else 
            grp_fu_400_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_403_ce_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_block_pp0_stage2_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            grp_fu_403_ce <= ap_const_logic_1;
        else 
            grp_fu_403_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_726_ce_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_block_pp0_stage2_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            grp_fu_726_ce <= ap_const_logic_1;
        else 
            grp_fu_726_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_726_p0 <= select_ln46_1_fu_478_p3(14 - 1 downto 0);
    grp_fu_726_p2 <= select_ln46_fu_501_p3(14 - 1 downto 0);
    grp_fu_93_p_ce <= grp_fu_393_ce;
    grp_fu_93_p_din0 <= select_ln46_reg_829_pp0_iter1_reg;
    icmp_ln46_fu_450_p2 <= "1" when (indvar_flatten_fu_98 = bound) else "0";
    icmp_ln47_fu_467_p2 <= "1" when (j_fu_90 = M) else "0";
    icmp_ln49_1_fu_571_p2 <= "1" when (trunc_ln49_fu_561_p1 = ap_const_lv52_0) else "0";
    icmp_ln49_fu_565_p2 <= "0" when (tmp_4_fu_551_p4 = ap_const_lv11_7FF) else "1";
    matrix_address0 <= zext_ln48_fu_522_p1(14 - 1 downto 0);

    matrix_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            matrix_ce0 <= ap_const_logic_1;
        else 
            matrix_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    or_ln49_fu_577_p2 <= (icmp_ln49_reg_870 or icmp_ln49_1_reg_875);

    out_r_TDATA_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_predicate_op150_write_state11, ap_predicate_op124_write_state10, ap_predicate_op106_write_state9, p_s_fu_618_p5, ap_block_pp0_stage1_01001, p_1_fu_647_p5, ap_block_pp0_stage2_01001, p_0_fu_693_p5, ap_block_pp0_stage0_01001)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op150_write_state11 = ap_const_boolean_1))) then 
            out_r_TDATA <= p_0_fu_693_p5;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_01001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_predicate_op124_write_state10 = ap_const_boolean_1))) then 
            out_r_TDATA <= p_1_fu_647_p5;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_01001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_predicate_op106_write_state9 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            out_r_TDATA <= p_s_fu_618_p5;
        else 
            out_r_TDATA <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    out_r_TDATA_blk_n_assign_proc : process(out_r_TREADY, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter2, ap_block_pp0_stage2, icmp_ln46_reg_805_pp0_iter2_reg, and_ln49_reg_880, p_V_load11_reg_888, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, p_V_load_1_reg_884, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, p_V_1_reg_924)
    begin
        if ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (p_V_1_reg_924 = ap_const_lv2_0)) or ((p_V_load_1_reg_884 = ap_const_lv2_0) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((p_V_load11_reg_888 = ap_const_lv2_3) and (ap_const_lv1_1 = and_ln49_reg_880) and (icmp_ln46_reg_805_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then 
            out_r_TDATA_blk_n <= out_r_TREADY;
        else 
            out_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    out_r_TVALID_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_predicate_op150_write_state11, ap_block_pp0_stage0_11001, ap_predicate_op124_write_state10, ap_block_pp0_stage2_11001, ap_predicate_op106_write_state9, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op150_write_state11 = ap_const_boolean_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_predicate_op106_write_state9 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_predicate_op124_write_state10 = ap_const_boolean_1)))) then 
            out_r_TVALID <= ap_const_logic_1;
        else 
            out_r_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    p_0_fu_693_p5 <= (((bitcast_ln174_11_fu_689_p1 & bitcast_ln174_10_fu_685_p1) & bitcast_ln174_9_fu_681_p1) & bitcast_ln174_8_fu_677_p1);
    p_1_fu_647_p5 <= (((bitcast_ln174_7_fu_643_p1 & bitcast_ln174_6_fu_639_p1) & bitcast_ln174_5_fu_635_p1) & bitcast_ln174_4_fu_631_p1);
    p_Result_s_fu_534_p3 <= (ap_const_lv1_0 & trunc_ln368_fu_530_p1);
    p_V_1_fu_660_p2 <= (p_V_fu_118 xor ap_const_lv2_2);
    p_V_2_fu_666_p2 <= std_logic_vector(unsigned(p_V_1_fu_660_p2) + unsigned(ap_const_lv2_1));
    p_s_fu_618_p5 <= (((bitcast_ln174_3_fu_614_p1 & bitcast_ln174_2_fu_610_p1) & bitcast_ln174_1_fu_606_p1) & bitcast_ln174_fu_602_p1);
    select_ln46_1_fu_478_p3 <= 
        add_ln46_1_fu_472_p2 when (icmp_ln47_fu_467_p2(0) = '1') else 
        i_fu_94;
    select_ln46_fu_501_p3 <= 
        ap_const_lv32_0 when (icmp_ln47_reg_814(0) = '1') else 
        j_load_reg_809;
    tmp_4_fu_551_p4 <= bitcast_ln49_fu_547_p1(62 downto 52);
    tmp_num0_1_out <= tmp_num0_5_reg_916;

    tmp_num0_1_out_ap_vld_assign_proc : process(ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            tmp_num0_1_out_ap_vld <= ap_const_logic_1;
        else 
            tmp_num0_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_num1_1_out <= tmp_num1_5_reg_908;

    tmp_num1_1_out_ap_vld_assign_proc : process(ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            tmp_num1_1_out_ap_vld <= ap_const_logic_1;
        else 
            tmp_num1_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_num2_1_out <= tmp_num2_5_reg_900;

    tmp_num2_1_out_ap_vld_assign_proc : process(ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            tmp_num2_1_out_ap_vld <= ap_const_logic_1;
        else 
            tmp_num2_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_num3_out <= tmp_num3_5_reg_892;

    tmp_num3_out_ap_vld_assign_proc : process(ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            tmp_num3_out_ap_vld <= ap_const_logic_1;
        else 
            tmp_num3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln368_fu_530_p1 <= data_V_fu_526_p1(31 - 1 downto 0);
    trunc_ln49_fu_561_p1 <= bitcast_ln49_fu_547_p1(52 - 1 downto 0);
    zext_ln48_fu_522_p0 <= grp_fu_726_p3;
    zext_ln48_fu_522_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln48_fu_522_p0),64));
end behav;
