// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="coo_dec_coo_dec,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.662000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=30,HLS_SYN_DSP=0,HLS_SYN_FF=1217,HLS_SYN_LUT=3937,HLS_VERSION=2022_1}" *)

module coo_dec (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_r_TDATA,
        in_r_TVALID,
        in_r_TREADY,
        out_r_TDATA,
        out_r_TVALID,
        out_r_TREADY
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [127:0] in_r_TDATA;
input   in_r_TVALID;
output   in_r_TREADY;
output  [127:0] out_r_TDATA;
output   out_r_TVALID;
input   out_r_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in_r_TDATA_blk_n;
reg    out_r_TDATA_blk_n;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg   [31:0] data_V_reg_700;
reg   [31:0] data_V_2_reg_705;
reg   [31:0] tmp_s_reg_710;
reg   [0:0] p_Result_s_reg_715;
reg   [7:0] xs_exp_V_reg_720;
wire   [22:0] p_Result_4_fu_221_p1;
reg   [22:0] p_Result_4_reg_726;
reg   [0:0] p_Result_5_reg_731;
reg   [7:0] xs_exp_V_2_reg_736;
reg   [22:0] p_Result_6_reg_742;
reg   [0:0] p_Result_7_reg_747;
reg   [7:0] xs_exp_V_3_reg_752;
reg   [22:0] p_Result_8_reg_758;
wire  signed [31:0] result_V_fu_384_p3;
reg  signed [31:0] result_V_reg_763;
wire    ap_CS_fsm_state2;
wire   [31:0] val_2_fu_480_p3;
reg   [31:0] val_2_reg_769;
wire   [31:0] result_V_17_fu_591_p3;
reg   [31:0] result_V_17_reg_775;
wire   [31:0] tmp_num1_fu_598_p1;
reg   [31:0] tmp_num1_reg_781;
wire    ap_CS_fsm_state3;
wire   [31:0] tmp_num2_fu_602_p1;
reg   [31:0] tmp_num2_reg_786;
wire   [31:0] tmp_num3_fu_606_p1;
reg   [31:0] tmp_num3_reg_791;
wire  signed [31:0] result_V_16_fu_615_p3;
wire   [13:0] trunc_ln58_fu_622_p1;
reg   [13:0] trunc_ln58_reg_801;
wire   [31:0] mul_i_fu_632_p2;
reg   [31:0] mul_i_reg_806;
wire   [31:0] mul_i3_fu_638_p2;
reg   [31:0] mul_i3_reg_811;
wire   [31:0] grp_fu_165_p1;
reg   [31:0] tmp_num0_reg_816;
wire    ap_CS_fsm_state6;
wire   [31:0] grp_fu_169_p1;
reg   [31:0] tmp_num1_1_reg_821;
wire   [127:0] p_0_fu_663_p5;
reg   [13:0] a_address0;
reg    a_ce0;
reg    a_we0;
reg   [31:0] a_d0;
wire   [31:0] a_q0;
wire    grp_coo_dec_Pipeline_1_fu_133_ap_start;
wire    grp_coo_dec_Pipeline_1_fu_133_ap_done;
wire    grp_coo_dec_Pipeline_1_fu_133_ap_idle;
wire    grp_coo_dec_Pipeline_1_fu_133_ap_ready;
wire   [13:0] grp_coo_dec_Pipeline_1_fu_133_a_address0;
wire    grp_coo_dec_Pipeline_1_fu_133_a_ce0;
wire    grp_coo_dec_Pipeline_1_fu_133_a_we0;
wire   [31:0] grp_coo_dec_Pipeline_1_fu_133_a_d0;
wire    grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_ap_start;
wire    grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_ap_done;
wire    grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_ap_idle;
wire    grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_ap_ready;
wire    grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_in_r_TREADY;
wire   [13:0] grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_a_address0;
wire    grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_a_ce0;
wire    grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_a_we0;
wire   [31:0] grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_a_d0;
wire    grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_ap_start;
wire    grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_ap_done;
wire    grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_ap_idle;
wire    grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_ap_ready;
wire    grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_out_r_TREADY;
wire   [127:0] grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_out_r_TDATA;
wire    grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_out_r_TVALID;
wire   [13:0] grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_a_address0;
wire    grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_a_ce0;
wire   [31:0] grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_tmp_num0_2_out;
wire    grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_tmp_num0_2_out_ap_vld;
wire   [31:0] grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_tmp_num1_3_out;
wire    grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_tmp_num1_3_out_ap_vld;
wire   [31:0] grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_p_out;
wire    grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_p_out_ap_vld;
wire   [31:0] grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_p_out1;
wire    grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_p_out1_ap_vld;
reg    grp_coo_dec_Pipeline_1_fu_133_ap_start_reg;
reg    ap_block_state1_ignore_call10;
reg    grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_ap_start_reg;
wire    ap_CS_fsm_state4;
reg    grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_ap_start_reg;
wire    ap_CS_fsm_state7;
reg    ap_block_state1;
wire   [24:0] mantissa_fu_281_p4;
wire   [8:0] zext_ln346_fu_294_p1;
wire   [8:0] add_ln346_fu_297_p2;
wire   [7:0] sub_ln1512_fu_311_p2;
wire   [0:0] isNeg_fu_303_p3;
wire  signed [8:0] sext_ln1512_fu_316_p1;
wire   [8:0] ush_fu_320_p3;
wire  signed [31:0] sext_ln1488_fu_328_p1;
wire   [78:0] zext_ln15_fu_290_p1;
wire   [78:0] zext_ln1488_fu_332_p1;
wire   [78:0] r_V_fu_336_p2;
wire   [0:0] tmp_fu_348_p3;
wire   [78:0] r_V_6_fu_342_p2;
wire   [31:0] zext_ln818_fu_356_p1;
wire   [31:0] tmp_4_fu_360_p4;
wire   [31:0] val_fu_370_p3;
wire   [31:0] result_V_9_fu_378_p2;
wire   [24:0] mantissa_2_fu_391_p4;
wire   [8:0] zext_ln346_1_fu_404_p1;
wire   [8:0] add_ln346_1_fu_407_p2;
wire   [7:0] sub_ln1512_1_fu_421_p2;
wire   [0:0] isNeg_2_fu_413_p3;
wire  signed [8:0] sext_ln1512_1_fu_426_p1;
wire   [8:0] ush_3_fu_430_p3;
wire  signed [31:0] sext_ln1488_2_fu_438_p1;
wire   [78:0] zext_ln15_2_fu_400_p1;
wire   [78:0] zext_ln1488_2_fu_442_p1;
wire   [78:0] r_V_7_fu_446_p2;
wire   [0:0] tmp_15_fu_458_p3;
wire   [78:0] r_V_8_fu_452_p2;
wire   [31:0] zext_ln818_1_fu_466_p1;
wire   [31:0] tmp_5_fu_470_p4;
wire   [24:0] mantissa_3_fu_488_p4;
wire   [8:0] zext_ln346_2_fu_501_p1;
wire   [8:0] add_ln346_2_fu_504_p2;
wire   [7:0] sub_ln1512_2_fu_518_p2;
wire   [0:0] isNeg_3_fu_510_p3;
wire  signed [8:0] sext_ln1512_2_fu_523_p1;
wire   [8:0] ush_4_fu_527_p3;
wire  signed [31:0] sext_ln1488_3_fu_535_p1;
wire   [78:0] zext_ln15_3_fu_497_p1;
wire   [78:0] zext_ln1488_3_fu_539_p1;
wire   [78:0] r_V_9_fu_543_p2;
wire   [0:0] tmp_19_fu_555_p3;
wire   [78:0] r_V_10_fu_549_p2;
wire   [31:0] zext_ln818_2_fu_563_p1;
wire   [31:0] tmp_6_fu_567_p4;
wire   [31:0] val_3_fu_577_p3;
wire   [31:0] result_V_15_fu_585_p2;
wire   [31:0] result_V_12_fu_610_p2;
wire   [31:0] empty_fu_627_p2;
wire   [31:0] bitcast_ln174_1_fu_659_p1;
wire   [31:0] bitcast_ln174_fu_655_p1;
reg    grp_fu_165_ce;
wire    ap_CS_fsm_state5;
reg    grp_fu_169_ce;
wire    regslice_both_out_r_U_apdone_blk;
reg    ap_block_state9;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    regslice_both_in_r_U_apdone_blk;
wire   [127:0] in_r_TDATA_int_regslice;
wire    in_r_TVALID_int_regslice;
reg    in_r_TREADY_int_regslice;
wire    regslice_both_in_r_U_ack_in;
reg   [127:0] out_r_TDATA_int_regslice;
reg    out_r_TVALID_int_regslice;
wire    out_r_TREADY_int_regslice;
wire    regslice_both_out_r_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 grp_coo_dec_Pipeline_1_fu_133_ap_start_reg = 1'b0;
#0 grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_ap_start_reg = 1'b0;
#0 grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_ap_start_reg = 1'b0;
end

coo_dec_a_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
a_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(a_address0),
    .ce0(a_ce0),
    .we0(a_we0),
    .d0(a_d0),
    .q0(a_q0)
);

coo_dec_coo_dec_Pipeline_1 grp_coo_dec_Pipeline_1_fu_133(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_coo_dec_Pipeline_1_fu_133_ap_start),
    .ap_done(grp_coo_dec_Pipeline_1_fu_133_ap_done),
    .ap_idle(grp_coo_dec_Pipeline_1_fu_133_ap_idle),
    .ap_ready(grp_coo_dec_Pipeline_1_fu_133_ap_ready),
    .a_address0(grp_coo_dec_Pipeline_1_fu_133_a_address0),
    .a_ce0(grp_coo_dec_Pipeline_1_fu_133_a_ce0),
    .a_we0(grp_coo_dec_Pipeline_1_fu_133_a_we0),
    .a_d0(grp_coo_dec_Pipeline_1_fu_133_a_d0)
);

coo_dec_coo_dec_Pipeline_VITIS_LOOP_16_1 grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_ap_start),
    .ap_done(grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_ap_done),
    .ap_idle(grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_ap_idle),
    .ap_ready(grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_ap_ready),
    .in_r_TVALID(in_r_TVALID_int_regslice),
    .tmp_num1_8(tmp_num1_reg_781),
    .tmp_num2_7(tmp_num2_reg_786),
    .tmp_num3(tmp_num3_reg_791),
    .mul_i(mul_i_reg_806),
    .in_r_TDATA(in_r_TDATA_int_regslice),
    .in_r_TREADY(grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_in_r_TREADY),
    .trunc_ln(trunc_ln58_reg_801),
    .a_address0(grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_a_address0),
    .a_ce0(grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_a_ce0),
    .a_we0(grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_a_we0),
    .a_d0(grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_a_d0)
);

coo_dec_coo_dec_Pipeline_VITIS_LOOP_58_1 grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_ap_start),
    .ap_done(grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_ap_done),
    .ap_idle(grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_ap_idle),
    .ap_ready(grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_ap_ready),
    .out_r_TREADY(grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_out_r_TREADY),
    .tmp_num0(tmp_num0_reg_816),
    .tmp_num1_1(tmp_num1_1_reg_821),
    .mul_i3(mul_i3_reg_811),
    .out_r_TDATA(grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_out_r_TDATA),
    .out_r_TVALID(grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_out_r_TVALID),
    .a_address0(grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_a_address0),
    .a_ce0(grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_a_ce0),
    .a_q0(a_q0),
    .tmp_num0_2_out(grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_tmp_num0_2_out),
    .tmp_num0_2_out_ap_vld(grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_tmp_num0_2_out_ap_vld),
    .tmp_num1_3_out(grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_tmp_num1_3_out),
    .tmp_num1_3_out_ap_vld(grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_tmp_num1_3_out_ap_vld),
    .p_out(grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_p_out),
    .p_out_ap_vld(grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_p_out_ap_vld),
    .p_out1(grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_p_out1),
    .p_out1_ap_vld(grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_p_out1_ap_vld)
);

coo_dec_sitofp_32s_32_4_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32s_32_4_no_dsp_1_U20(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(result_V_reg_763),
    .ce(grp_fu_165_ce),
    .dout(grp_fu_165_p1)
);

coo_dec_sitofp_32s_32_4_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32s_32_4_no_dsp_1_U21(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(result_V_16_fu_615_p3),
    .ce(grp_fu_169_ce),
    .dout(grp_fu_169_p1)
);

coo_dec_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U22(
    .din0(result_V_16_fu_615_p3),
    .din1(result_V_reg_763),
    .dout(mul_i3_fu_638_p2)
);

coo_dec_regslice_both #(
    .DataWidth( 128 ))
regslice_both_in_r_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_r_TDATA),
    .vld_in(in_r_TVALID),
    .ack_in(regslice_both_in_r_U_ack_in),
    .data_out(in_r_TDATA_int_regslice),
    .vld_out(in_r_TVALID_int_regslice),
    .ack_out(in_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_r_U_apdone_blk)
);

coo_dec_regslice_both #(
    .DataWidth( 128 ))
regslice_both_out_r_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_r_TDATA_int_regslice),
    .vld_in(out_r_TVALID_int_regslice),
    .ack_in(out_r_TREADY_int_regslice),
    .data_out(out_r_TDATA),
    .vld_out(regslice_both_out_r_U_vld_out),
    .ack_out(out_r_TREADY),
    .apdone_blk(regslice_both_out_r_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_coo_dec_Pipeline_1_fu_133_ap_start_reg <= 1'b0;
    end else begin
        if ((~((in_r_TVALID_int_regslice == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_coo_dec_Pipeline_1_fu_133_ap_start_reg <= 1'b1;
        end else if ((grp_coo_dec_Pipeline_1_fu_133_ap_ready == 1'b1)) begin
            grp_coo_dec_Pipeline_1_fu_133_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_ap_start_reg <= 1'b1;
        end else if ((grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_ap_ready == 1'b1)) begin
            grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_ap_start_reg <= 1'b1;
        end else if ((grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_ap_ready == 1'b1)) begin
            grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        data_V_2_reg_705 <= {{in_r_TDATA_int_regslice[95:64]}};
        data_V_reg_700 <= {{in_r_TDATA_int_regslice[63:32]}};
        p_Result_4_reg_726 <= p_Result_4_fu_221_p1;
        p_Result_5_reg_731 <= in_r_TDATA_int_regslice[32'd63];
        p_Result_6_reg_742 <= {{in_r_TDATA_int_regslice[54:32]}};
        p_Result_7_reg_747 <= in_r_TDATA_int_regslice[32'd95];
        p_Result_8_reg_758 <= {{in_r_TDATA_int_regslice[86:64]}};
        p_Result_s_reg_715 <= in_r_TDATA_int_regslice[32'd31];
        tmp_s_reg_710 <= {{in_r_TDATA_int_regslice[127:96]}};
        xs_exp_V_2_reg_736 <= {{in_r_TDATA_int_regslice[62:55]}};
        xs_exp_V_3_reg_752 <= {{in_r_TDATA_int_regslice[94:87]}};
        xs_exp_V_reg_720 <= {{in_r_TDATA_int_regslice[30:23]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mul_i3_reg_811 <= mul_i3_fu_638_p2;
        mul_i_reg_806 <= mul_i_fu_632_p2;
        tmp_num1_reg_781 <= tmp_num1_fu_598_p1;
        tmp_num2_reg_786 <= tmp_num2_fu_602_p1;
        tmp_num3_reg_791 <= tmp_num3_fu_606_p1;
        trunc_ln58_reg_801 <= trunc_ln58_fu_622_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        result_V_17_reg_775 <= result_V_17_fu_591_p3;
        result_V_reg_763 <= result_V_fu_384_p3;
        val_2_reg_769 <= val_2_fu_480_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_num0_reg_816 <= grp_fu_165_p1;
        tmp_num1_1_reg_821 <= grp_fu_169_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        a_address0 = grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_a_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        a_address0 = grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_a_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        a_address0 = grp_coo_dec_Pipeline_1_fu_133_a_address0;
    end else begin
        a_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        a_ce0 = grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_a_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        a_ce0 = grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_a_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        a_ce0 = grp_coo_dec_Pipeline_1_fu_133_a_ce0;
    end else begin
        a_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        a_d0 = grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_a_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        a_d0 = grp_coo_dec_Pipeline_1_fu_133_a_d0;
    end else begin
        a_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        a_we0 = grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_a_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        a_we0 = grp_coo_dec_Pipeline_1_fu_133_a_we0;
    end else begin
        a_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((in_r_TVALID_int_regslice == 1'b0) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_coo_dec_Pipeline_1_fu_133_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((out_r_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((out_r_TREADY_int_regslice == 1'b0) | (regslice_both_out_r_U_apdone_blk == 1'b1))) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((out_r_TREADY_int_regslice == 1'b0) | (regslice_both_out_r_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((out_r_TREADY_int_regslice == 1'b0) | (regslice_both_out_r_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state6) | ((1'b1 == ap_CS_fsm_state4) & (grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_ap_done == 1'b1)))) begin
        grp_fu_165_ce = 1'b1;
    end else begin
        grp_fu_165_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state6) | ((1'b1 == ap_CS_fsm_state4) & (grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_ap_done == 1'b1)))) begin
        grp_fu_169_ce = 1'b1;
    end else begin
        grp_fu_169_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        in_r_TDATA_blk_n = in_r_TVALID_int_regslice;
    end else begin
        in_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((in_r_TVALID_int_regslice == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        in_r_TREADY_int_regslice = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        in_r_TREADY_int_regslice = grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_in_r_TREADY;
    end else begin
        in_r_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        out_r_TDATA_blk_n = out_r_TREADY_int_regslice;
    end else begin
        out_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((out_r_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        out_r_TDATA_int_regslice = p_0_fu_663_p5;
    end else if (((1'b1 == ap_CS_fsm_state7) & (grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_out_r_TVALID == 1'b1))) begin
        out_r_TDATA_int_regslice = grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_out_r_TDATA;
    end else begin
        out_r_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((out_r_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        out_r_TVALID_int_regslice = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        out_r_TVALID_int_regslice = grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_out_r_TVALID;
    end else begin
        out_r_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((in_r_TVALID_int_regslice == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_coo_dec_Pipeline_1_fu_133_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((out_r_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if ((~((out_r_TREADY_int_regslice == 1'b0) | (regslice_both_out_r_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln346_1_fu_407_p2 = ($signed(zext_ln346_1_fu_404_p1) + $signed(9'd385));

assign add_ln346_2_fu_504_p2 = ($signed(zext_ln346_2_fu_501_p1) + $signed(9'd385));

assign add_ln346_fu_297_p2 = ($signed(zext_ln346_fu_294_p1) + $signed(9'd385));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((in_r_TVALID_int_regslice == 1'b0) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call10 = ((in_r_TVALID_int_regslice == 1'b0) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state9 = ((out_r_TREADY_int_regslice == 1'b0) | (regslice_both_out_r_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bitcast_ln174_1_fu_659_p1 = grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_tmp_num1_3_out;

assign bitcast_ln174_fu_655_p1 = grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_tmp_num0_2_out;

assign empty_fu_627_p2 = result_V_17_reg_775 << 32'd2;

assign grp_coo_dec_Pipeline_1_fu_133_ap_start = grp_coo_dec_Pipeline_1_fu_133_ap_start_reg;

assign grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_ap_start = grp_coo_dec_Pipeline_VITIS_LOOP_16_1_fu_139_ap_start_reg;

assign grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_ap_start = grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_ap_start_reg;

assign grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_out_r_TREADY = (out_r_TREADY_int_regslice & ap_CS_fsm_state7);

assign in_r_TREADY = regslice_both_in_r_U_ack_in;

assign isNeg_2_fu_413_p3 = add_ln346_1_fu_407_p2[32'd8];

assign isNeg_3_fu_510_p3 = add_ln346_2_fu_504_p2[32'd8];

assign isNeg_fu_303_p3 = add_ln346_fu_297_p2[32'd8];

assign mantissa_2_fu_391_p4 = {{{{1'd1}, {p_Result_6_reg_742}}}, {1'd0}};

assign mantissa_3_fu_488_p4 = {{{{1'd1}, {p_Result_8_reg_758}}}, {1'd0}};

assign mantissa_fu_281_p4 = {{{{1'd1}, {p_Result_4_reg_726}}}, {1'd0}};

assign mul_i_fu_632_p2 = (empty_fu_627_p2 - result_V_17_reg_775);

assign out_r_TVALID = regslice_both_out_r_U_vld_out;

assign p_0_fu_663_p5 = {{{{grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_p_out1}, {grp_coo_dec_Pipeline_VITIS_LOOP_58_1_fu_151_p_out}}, {bitcast_ln174_1_fu_659_p1}}, {bitcast_ln174_fu_655_p1}};

assign p_Result_4_fu_221_p1 = in_r_TDATA_int_regslice[22:0];

assign r_V_10_fu_549_p2 = zext_ln15_3_fu_497_p1 << zext_ln1488_3_fu_539_p1;

assign r_V_6_fu_342_p2 = zext_ln15_fu_290_p1 << zext_ln1488_fu_332_p1;

assign r_V_7_fu_446_p2 = zext_ln15_2_fu_400_p1 >> zext_ln1488_2_fu_442_p1;

assign r_V_8_fu_452_p2 = zext_ln15_2_fu_400_p1 << zext_ln1488_2_fu_442_p1;

assign r_V_9_fu_543_p2 = zext_ln15_3_fu_497_p1 >> zext_ln1488_3_fu_539_p1;

assign r_V_fu_336_p2 = zext_ln15_fu_290_p1 >> zext_ln1488_fu_332_p1;

assign result_V_12_fu_610_p2 = (32'd0 - val_2_reg_769);

assign result_V_15_fu_585_p2 = (32'd0 - val_3_fu_577_p3);

assign result_V_16_fu_615_p3 = ((p_Result_5_reg_731[0:0] == 1'b1) ? result_V_12_fu_610_p2 : val_2_reg_769);

assign result_V_17_fu_591_p3 = ((p_Result_7_reg_747[0:0] == 1'b1) ? result_V_15_fu_585_p2 : val_3_fu_577_p3);

assign result_V_9_fu_378_p2 = (32'd0 - val_fu_370_p3);

assign result_V_fu_384_p3 = ((p_Result_s_reg_715[0:0] == 1'b1) ? result_V_9_fu_378_p2 : val_fu_370_p3);

assign sext_ln1488_2_fu_438_p1 = $signed(ush_3_fu_430_p3);

assign sext_ln1488_3_fu_535_p1 = $signed(ush_4_fu_527_p3);

assign sext_ln1488_fu_328_p1 = $signed(ush_fu_320_p3);

assign sext_ln1512_1_fu_426_p1 = $signed(sub_ln1512_1_fu_421_p2);

assign sext_ln1512_2_fu_523_p1 = $signed(sub_ln1512_2_fu_518_p2);

assign sext_ln1512_fu_316_p1 = $signed(sub_ln1512_fu_311_p2);

assign sub_ln1512_1_fu_421_p2 = (8'd127 - xs_exp_V_2_reg_736);

assign sub_ln1512_2_fu_518_p2 = (8'd127 - xs_exp_V_3_reg_752);

assign sub_ln1512_fu_311_p2 = (8'd127 - xs_exp_V_reg_720);

assign tmp_15_fu_458_p3 = r_V_7_fu_446_p2[32'd24];

assign tmp_19_fu_555_p3 = r_V_9_fu_543_p2[32'd24];

assign tmp_4_fu_360_p4 = {{r_V_6_fu_342_p2[55:24]}};

assign tmp_5_fu_470_p4 = {{r_V_8_fu_452_p2[55:24]}};

assign tmp_6_fu_567_p4 = {{r_V_10_fu_549_p2[55:24]}};

assign tmp_fu_348_p3 = r_V_fu_336_p2[32'd24];

assign tmp_num1_fu_598_p1 = data_V_reg_700;

assign tmp_num2_fu_602_p1 = data_V_2_reg_705;

assign tmp_num3_fu_606_p1 = tmp_s_reg_710;

assign trunc_ln58_fu_622_p1 = result_V_16_fu_615_p3[13:0];

assign ush_3_fu_430_p3 = ((isNeg_2_fu_413_p3[0:0] == 1'b1) ? sext_ln1512_1_fu_426_p1 : add_ln346_1_fu_407_p2);

assign ush_4_fu_527_p3 = ((isNeg_3_fu_510_p3[0:0] == 1'b1) ? sext_ln1512_2_fu_523_p1 : add_ln346_2_fu_504_p2);

assign ush_fu_320_p3 = ((isNeg_fu_303_p3[0:0] == 1'b1) ? sext_ln1512_fu_316_p1 : add_ln346_fu_297_p2);

assign val_2_fu_480_p3 = ((isNeg_2_fu_413_p3[0:0] == 1'b1) ? zext_ln818_1_fu_466_p1 : tmp_5_fu_470_p4);

assign val_3_fu_577_p3 = ((isNeg_3_fu_510_p3[0:0] == 1'b1) ? zext_ln818_2_fu_563_p1 : tmp_6_fu_567_p4);

assign val_fu_370_p3 = ((isNeg_fu_303_p3[0:0] == 1'b1) ? zext_ln818_fu_356_p1 : tmp_4_fu_360_p4);

assign zext_ln1488_2_fu_442_p1 = $unsigned(sext_ln1488_2_fu_438_p1);

assign zext_ln1488_3_fu_539_p1 = $unsigned(sext_ln1488_3_fu_535_p1);

assign zext_ln1488_fu_332_p1 = $unsigned(sext_ln1488_fu_328_p1);

assign zext_ln15_2_fu_400_p1 = mantissa_2_fu_391_p4;

assign zext_ln15_3_fu_497_p1 = mantissa_3_fu_488_p4;

assign zext_ln15_fu_290_p1 = mantissa_fu_281_p4;

assign zext_ln346_1_fu_404_p1 = xs_exp_V_2_reg_736;

assign zext_ln346_2_fu_501_p1 = xs_exp_V_3_reg_752;

assign zext_ln346_fu_294_p1 = xs_exp_V_reg_720;

assign zext_ln818_1_fu_466_p1 = tmp_15_fu_458_p3;

assign zext_ln818_2_fu_563_p1 = tmp_19_fu_555_p3;

assign zext_ln818_fu_356_p1 = tmp_fu_348_p3;


reg find_kernel_block = 0;
// synthesis translate_off
`include "coo_dec_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //coo_dec

